_G.ZH = _G.ZH or {}
local t = {
["AntiCheat & Bypass"]="反作弊与绕过",["Main"]="主功能",["Player"]="玩家",["Combat"]="战斗",["Gun Mods"]="枪械修改",["Infected"]="感染者",["ESP"]="透视",["Visuals"]="视觉",["World"]="世界",["Animations"]="动画",["Quests"]="任务",["Utilities"]="实用工具",["Settings"]="设置",
["Warning"]="警告",["Compatibility"]="兼容性",["Network Bypass"]="网络绕过",["Executor"]="执行器",["Device"]="设备",["Hook Support"]="Hook 支持",["Account"]="账号",["Apply Network Bypass"]="应用网络绕过",["Bypass"]="绕过",["Movement Bypass"]="移动绕过",["Read before using!"]="使用前请阅读！",["Supported (Silent Aim OK)"]="支持（静默瞄准可用）",["NOT supported (Silent Aim may fail)"]="不支持（静默瞄准可能失效）",["Enable this to make the selected features undetected. Does NOT activate them."]="启用此功能使所选功能不被检测。不会激活它们。",["Select which features should be made undetected when used."]="选择哪些功能在使用时不被检测。",["Not supported by your executor"]="你的执行器不支持此功能",["Locked For Security Reason..."]="因安全原因锁定...",
["Character Health"]="角色生命值",["Suicide"]="自杀",["Suicide with Animation"]="带动画自杀",["Fake Death"]="假死",["Fake Injured (idle)"]="假装受伤（闲置）",["Animator"]="动画器",["Apply Animator Config"]="应用动画器配置",["Idle Animation"]="闲置动画",["Walk Animation"]="行走动画",["Run Animation"]="奔跑动画",["Customization"]="自定义",["Character Name"]="角色名称",["Rank"]="军衔",["Nametag Color"]="名牌颜色",["Team"]="队伍",["Enter name"]="输入名称",["Enter rank"]="输入军衔",
["Walkspeed Settings"]="行走速度设置",["Enable Speed Modifiers"]="启用速度修改",["WalkSpeed"]="行走速度",["Infinite Stamina"]="无限耐力",["Jump Settings"]="跳跃设置",["Enable JumpPower"]="启用跳跃力",["JumpPower"]="跳跃力",["Infinite Jump"]="无限跳跃",["Bypass Jump AC"]="绕过跳跃反作弊",["Fly"]="飞行",["Enable Fly"]="启用飞行",["Fly Method"]="飞行方式",["Seat [UNDETECTED]"]="座椅 [未被检测]",["Fly Speed"]="飞行速度",["Noclip"]="穿墙",["Enable Noclip"]="启用穿墙",["Patch"]="补丁",["Disable Stagger"]="禁用硬直",["Anti-Anchor"]="防锚定",["Allow you to move while executing / getting executed"]="允许你在处决/被处决时移动",
["Free Tools"]="免费工具",["Get FlashLight"]="获取手电筒",["Bring Weapons"]="携带武器",["Auto Bring Axe"]="自动携带斧头",["Auto Bring Hammer"]="自动携带锤子",["Delete Mobs Protections"]="删除怪物保护",["Delete All Shields"]="删除所有护盾",["Auto-Remove Shields"]="自动移除护盾",["Delete Slasher Axe"]="删除 Slasher 斧头",["Auto-Remove Axe"]="自动移除斧头",["Anti Riser Dodge"]="防 Riser 闪避",["Prevents risers from dodging"]="阻止 Riser 闪避",
}
for k, v in pairs(t) do _G.ZH[k] = v end
