_G.ZH = _G.ZH or {}
local t = {
["View Model"]="视图模型",["Enable VM customizations"]="启用视图模型自定义",["VM Color"]="视图模型颜色",["VM Material"]="视图模型材质",["Custom Weapons Appearance"]="自定义武器外观",["Enable custom Weapons Appearance"]="启用自定义武器外观",["Weapons Color"]="武器颜色",["Weapons Material"]="武器材质",
["Silent Aim"]="静默瞄准",["Enable Silent Aim"]="启用静默瞄准",["Enable Wall Check"]="启用墙体检测",["Target Part"]="目标部位",["Head"]="头部",["Torso"]="躯干",["Show FOV Circle"]="显示 FOV 圆圈",["FOV Circle Radius"]="FOV 圆圈半径",["FOV Circle Mode"]="FOV 圆圈模式",["Center"]="中心",["Mouse"]="鼠标",["Reload"]="换弹",["Fast Reload Boosts"]="快速换弹加成",["Fast Reload"]="快速换弹",["Auto Reload"]="自动换弹",["Instant Shotgun Reload"]="瞬间霰弹枪换弹",["Bullet Visualizer"]="子弹可视化",["Is missed"]="未命中",["Is Succes"]="成功",["Loading"]="加载中",["Enable Bullet Visualizer"]="启用子弹可视化",["Hitbox"]="命中框",["Box Size"]="框大小",["Enable Hitbox Expander"]="启用命中框扩展器",["No Recoil"]="无后坐力",["Silencer"]="消音器",["Infinite Ammo"]="无限弹药",
["Player Infection"]="玩家感染",["Fake Controllable Infected"]="假装可控感染者",["Fake Non-Controllable Infected"]="假装不可控感染者",["Get Infected [BETA]"]="被感染 [BETA]",["CI Fight Mods"]="CI 战斗修改",["Auto Complete QTE"]="自动完成 QTE",["Auto QTE Platform"]="自动 QTE 平台",["PC"]="电脑",["Mobile"]="移动端",["Console"]="主机",["QTE Trigger Speed"]="QTE 触发速度",
["Global ESP Settings"]="全局透视设置",["Outline Transparency"]="轮廓透明度",["Highlight Transparency"]="高亮透明度",["Max Distance"]="最大距离",["Box Thickness"]="框线粗细",["Players ESP Settings"]="玩家透视设置",["Players Color"]="玩家颜色",["Highlight Players"]="高亮玩家",["Box Players"]="玩家方框",["Show Players Name"]="显示玩家名称",["Show Players Health"]="显示玩家生命值",["Show Players Distance"]="显示玩家距离",["Mobs ESP Settings"]="怪物透视设置",["Mobs Color"]="怪物颜色",["Highlight Mobs"]="高亮怪物",["Box Mobs"]="怪物方框",["Show Mobs Name"]="显示怪物名称",["Show Mobs Health"]="显示怪物生命值",["Show Mobs Distance"]="显示怪物距离",["Boss ESP Settings"]="Boss 透视设置",["Boss Color"]="Boss 颜色",["Highlight Bosses"]="高亮 Boss",["Box Bosses"]="Boss 方框",["Show Bosses Name"]="显示 Boss 名称",["Show Bosses Health"]="显示 Boss 生命值",["Show Bosses Distance"]="显示 Boss 距离",
["Camera Settings"]="相机设置",["Unlock Third Person"]="解锁第三人称",["Custom FOV"]="自定义 FOV",["Field of View"]="视野范围",["Atmosphere"]="大气",["Full Bright"]="全亮",["No Fog"]="无雾",["Xray Settings"]="Xray 设置",["Enable X-Ray"]="启用 X-Ray",["Distance"]="距离",["Transparency"]="透明度",["Material"]="材质",["Screen Customization"]="屏幕自定义",["Auto-Wipe Screen Blood"]="自动清除屏幕血迹",["Clean Screen"]="清洁屏幕",["Night Vision & Gasmask"]="夜视仪与防毒面具",["Delete Gasmask"]="删除防毒面具",["Break Gasmask"]="破坏防毒面具",["Infinite Night Vision"]="无限夜视",
["Teleport"]="传送",["Sector 1"]="第一区",["Sector 2"]="第二区",["Sector 3"]="第三区",["Spawn"]="出生点",["Generator 1"]="发电机 1",["Generator 2"]="发电机 2",["Reactor 4"]="反应堆 4",["Mutant"]="变种人",["Valve"]="阀门",["Sector entrance"]="区域入口",["Russman's office"]="Russman 办公室",["Armory"]="军械库",["Keycard"]="钥匙卡",
["LandMines"]="地雷",["Delete All Landmines"]="删除所有地雷",["Radiations"]="辐射",["Anti-Radiation Effect"]="防辐射效果",["Remove Elephant Foot"]="移除象脚",["Terror UI"]="恐怖 UI",["Disable ChimeraRad"]="禁用 ChimeraRad",["Disable GilbertRad"]="禁用 GilbertRad",["Map Remover"]="地图移除器",["Remove Arabic dud"]="移除阿拉伯假人",["Remove Lobby Music"]="移除大厅音乐",["Delete ALL doors"]="删除所有门",
["Toggle Animations"]="切换动画",["Button Animations"]="按钮动画",
["Quest Completion"]="任务完成",["Complete Manhattan Radiation Quest"]="完成曼哈顿辐射任务",["Collect All Documents"]="收集所有文件",["Get Badges"]="获取徽章",["Get Underequipped Badge"]="获取装备不足徽章",["Get 'Unfortunate' Badge"]="获取「不幸」徽章",["Get 'NECROTIC-CONTROL' Badge"]="获取「坏死控制」徽章",["Get 'SECTOR-SWEEP' Badge"]="获取「区域清扫」徽章",
["Main Stuff"]="主要功能",["Go to Restricted Server"]="前往限制服务器",["Anti-AFK"]="防挂机",["Auto Remove Death Screen"]="自动移除死亡屏幕",["Proximity Prompt"]="接近提示",["Instant proximity prompt"]="瞬间接近提示",["Auto Proximity Prompt"]="自动接近提示",
["Danger Zone"]="危险区域",["Delete Script"]="删除脚本",["Interface"]="界面",["UI Theme"]="UI 主题",["Minimize Keybind"]="最小化快捷键",["Sentinel Status"]="Sentinel 状态",
["Success"]="成功",["Failed"]="失败",["Error"]="错误",["Info"]="信息",["Documents"]="文件",["Manhattan Quest"]="曼哈顿任务",["Infection"]="感染",
}
for k, v in pairs(t) do _G.ZH[k] = v end
